### ISSUE TITLE
Self-hosted web app built but incorrectly

### ISSUE THREAD

**Issue by sampittko** [hubtype/botonic#1199]
**Describe the bug**
When proceeding according to [docs](https://botonic.io/docs/deployment/standalone-js-bundle) in order to build standalone JS bundle for chatbot, the only output file is `/dist/main.js`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create blank Botonic project
2. Proceed according to docs for standalone JS bundle deployment type
3. Build the project
4. See code generated by webpack that is unusable

**What is the expected behaviour?**
Generate `dist/webchat.botonic.js` which can be imported to any website.

**Screenshots**
Build log
![Screen Shot 2020-12-18 at 19 57 24](https://user-images.githubusercontent.com/38221262/102650453-40d5ed80-416b-11eb-942c-531cf92e782b.png)

Folder structure after reproducing steps from docs:
![Screen Shot 2020-12-18 at 19 54 06](https://user-images.githubusercontent.com/38221262/102650200-cc02b380-416a-11eb-9e54-b6a6fc6a4238.png)

**About the environment**
Botonic CLI v0.16.0
Node v15.4.0

**Additional context**
No additional dependencies, just what is included for blank Botonic project

**Comment by ChristopherGS** [comment]
@dpinol I can confirm that we've also just encountered this same bug (tested on node v12 and v14, and on Windows 10 and MacOS). We end up with just the `main.js` file in the `dist` directory. I'll begin investigating now, would really appreciate any guidance.

**Comment by ChristopherGS** [comment]
*update*
Progress so far: I've now fixed the webpack config so that the correct file is output. I updated webpack.config.js like so (note quite a few differences from the docs):

```
...
function botonicSelfHostedConfig(mode) {
  return {
    optimization: optimizationConfig,
    mode: mode,
    devtool: sourceMap(mode),
    target: 'web',
    entry: path.resolve('webpack-entries', 'self-hosted-entry.js'),
    module: {
      rules: [babelLoaderConfig, fileLoaderConfig(path.join('..', ASSETS_DIRNAME)), stylesLoaderConfig],
    },
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'webchat.botonic.js',
      library: 'Botonic',
      libraryTarget: 'umd',
      libraryExport: 'app',
      publicPath: './',
    },
    resolve: resolveConfig,
    plugins: [
      imageminPlugin,
      new webpack.DefinePlugin({
        IS_BROWSER: false,
        IS_NODE: true,
        HUBTYPE_API_URL: null,
        BOTONIC_TARGET: BOTONIC_TARGETS.DEV,
      }),
    ],
  }
}

module.exports = (env, argv) => {
  if (env.target === BOTONIC_TARGETS.ALL) {
    return [
      botonicNodeConfig(argv.mode),
      botonicWebviewsConfig(argv.mode),
      botonicWebchatConfig(argv.mode),
    ]
  } else if (env.target === BOTONIC_TARGETS.DEV) {
    return [botonicDevConfig(argv.mode)]
  } else if (env.target === BOTONIC_TARGETS.NODE) {
    return [botonicNodeConfig(argv.mode)]
  } else if (env.target === BOTONIC_TARGETS.WEBVIEWS) {
    return [botonicWebviewsConfig(argv.mode)]
  } else if (env.target === BOTONIC_TARGETS.WEBCHAT) {
    return [botonicWebchatConfig(argv.mode)]
  } else if (env.target === 'self-hosted') {
    return [botonicSelfHostedConfig(argv.mode)]
  } else {
    return null
  }
}
```

I then realized that in any given HTML you need to invoke the chatbot like so:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>title</title>
    <script src="webchat.botonic.js"></script>
</head>
<body>
<h1>test</h1>
<div id="root"></div>
<script> type="text/javascript">
    document.addEventListener('DOMContentLoaded', function(event) {
        Botonic.render(document.getElementById('root'), )
    })
</script>
<!-- page content -->
</body>
</html>
```

This gets me a chatbot widget that can expand, and loads my custom cover. However, the text and buttons are not showing correctly. Here's the change I made to get it this far:

```
...

// my attempt
import {webchat} from "../webchat";

export class SelfHostedApp extends WebchatApp {
    constructor({
                    theme = {},
                    persistentMenu,
                    blockInputs,
                    emojiPicker,
                    enableAttachments,
                    onInit,
                    onOpen,
                    onClose,
                    onMessage,
                    ...botOptions
                }) {
        super({
            theme,
            persistentMenu,
            blockInputs,
            emojiPicker,
            enableAttachments,
            onInit,
            onOpen,
            onClose,
            onMessage,
        })
        this.bot = new ReactBot({
            ...botOptions,
        })
    }
    
    // Passing in webchat
    render(dest, optionsAtRuntime = webchat) {
        let {
            theme = {},
            persistentMenu,
            blockInputs,
            emojiPicker,
            enableAttachments,
            onInit,
            onOpen,
            onClose,
            onMessage,
            ...webchatOptions
        } = optionsAtRuntime
        theme = { ...this.theme, ...theme }
        persistentMenu = persistentMenu || this.persistentMenu
        blockInputs = blockInputs || this.blockInputs
        emojiPicker = emojiPicker || this.emojiPicker
        enableAttachments = enableAttachments || this.enableAttachments
        this.onInit = onInit || this.onInit
        this.onOpen = onOpen || this.onOpen
        this.onClose = onClose || this.onClose
        this.onMessage = onMessage || this.onMessage
        render(
            <Webchat
                ref={this.webchatRef}
                {...webchatOptions}
                theme={theme}
                persistentMenu={persistentMenu}
                blockInputs={blockInputs}
                emojiPicker={emojiPicker}
                enableAttachments={enableAttachments}
                getString={(stringId, session) => this.bot.getString(stringId, session)}
                setLocale={(locale, session) => this.bot.setLocale(locale, session)}
                onInit={(...args) => this.onInitWebchat(...args)}
                onOpen={(...args) => this.onOpenWebchat(...args)}
                onClose={(...args) => this.onCloseWebchat(...args)}
                onUserInput={(...args) => this.onUserInput(...args)}
            />,
            dest
        )
    }

    async onUserInput({ input, session, lastRoutePath }) {
        this.onMessage && this.onMessage(this, { from: 'user', message: input })
        let resp = await this.bot.input({ input, session, lastRoutePath })
        this.onMessage &&
        resp.response.map(r => this.onMessage(this, { from: 'bot', message: r }))
        this.webchatRef.current.addBotResponse(resp)
    }
}
```

My guess is that there are some other configs that need to be passed in. Continuing my investigation now, but any help would be greatly appreciated @marcrabat

**Comment by ChristopherGS** [comment]
Display currently when deployed: 
![image](https://user-images.githubusercontent.com/5574524/106881224-28973f00-66d5-11eb-8ffb-f6357f35bb40.png)

How it looks when running locally:
![image](https://user-images.githubusercontent.com/5574524/106881327-495f9480-66d5-11eb-8815-54a146f2cbc9.png)

**Comment by ChristopherGS** [comment]
Can confirm that this behavior is not limited to my app. Just ran the self-hosted deploy with the botonic telco example and got similar results: 

![image](https://user-images.githubusercontent.com/5574524/106884705-8f1e5c00-66d9-11eb-9c2d-33d5e8f49897.png)

**Comment by vanbasten17** [comment]
Hi @ChristopherGS , by seeing the screenshots I think that this can be related on how the rendering logic is resolved. If you want to investigate further, I think it would be interesting to see these pieces of code in `@botonic/core`:
IS_NODE and IS_BROWSER are env variables resolved by webpack at build time. It seems that it is not resolving the environment as expected.
```
export const isNode = () => {
  return typeof IS_NODE !== 'undefined'
    ? // eslint-disable-next-line no-undef
      IS_NODE
    : typeof process !== 'undefined' &&
        process.versions !== null &&
        process.versions.node !== null
}

export const isBrowser = () => {
  return typeof IS_BROWSER !== 'undefined'
    ? // eslint-disable-next-line no-undef
      IS_BROWSER
    : typeof window !== 'undefined' &&
        typeof window.document !== 'undefined' &&
        !window.process
}
```

**Comment by ChristopherGS** [comment]
> Hi @ChristopherGS , by seeing the screenshots I think that this can be related on how the rendering logic is resolved. If you want to investigate further, I think it would be interesting to see these pieces of code in `@botonic/core`:
> IS_NODE and IS_BROWSER are env variables resolved by webpack at build time. It seems that it is not resolving the environment as expected.
> 
> ```
> export const isNode = () => {
>   return typeof IS_NODE !== 'undefined'
>     ? // eslint-disable-next-line no-undef
>       IS_NODE
>     : typeof process !== 'undefined' &&
>         process.versions !== null &&
>         process.versions.node !== null
> }
> 
> export const isBrowser = () => {
>   return typeof IS_BROWSER !== 'undefined'
>     ? // eslint-disable-next-line no-undef
>       IS_BROWSER
>     : typeof window !== 'undefined' &&
>         typeof window.document !== 'undefined' &&
>         !window.process
> }
> ```

Thanks @vanbasten17 that was it!

In `webpack.config.js`, in the `botonicSelfHostedConfig` plugins array, setting:
```
IS_BROWSER: true
```

Fixed the issue. In hindsight obvious, but really appreciate the push. I'll be happy to do a PR updating the docs for the next person.

**Comment by vanbasten17** [comment]
Cool!! Good effort @ChristopherGS ! Please, go ahead with the PR, you're welcome 😊

**Comment by vanbasten17** [comment]
I think it's only necessary to update this part of the docs :)

**Comment by vanbasten17** [comment]
Here the file that needs to be updated: https://github.com/hubtype/botonic/blob/master/docs/docs/deployment/standalone-js-bundle.md
