### ISSUE TITLE
A problem with npm run train / botonic train

### ISSUE THREAD

**Issue by crtdaniele** [hubtype/botonic#1210]
When I try to launch npm run train or botonic train I have this error in the terminal:

node-pre-gyp info This Node instance does not support builds for N-API version 7
node-pre-gyp info This Node instance does not support builds for N-API version 7
2020-12-21 10:54:55.496263: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Found '10k-fasttext-300d-en.db'.
Orthogonal initializer is being called on a matrix with more than 2000 (65536) elements: Slowness may result.
_________________________________________________________________
Layer (type)                 Output shape              Param #   
=================================================================
embedding_Embedding1 (Embedd [null,20,300]             1800
_________________________________________________________________
lstm_LSTM1 (LSTM)            [null,128]                219648
_________________________________________________________________
dense_Dense1 (Dense)         [null,1]                  129
=================================================================
Total params: 221577
Trainable params: 221577
Non-trainable params: 0
_________________________________________________________________
Epoch 1 / 8
(node:13040) UnhandledPromiseRejectionWarning: Error: Error in oneHot: depth must be >=2, but it is 1
    at oneHot_ (D:\lavoro\sviluppo\apps\marmallade.chat\node_modules\@tensorflow\tfjs-core\src\ops\one_hot.ts:51:11)
    at Object.tfc.oneHot (D:\lavoro\sviluppo\apps\marmallade.chat\node_modules\@tensorflow\tfjs-core\src\ops\operation.ts:51:24)
    at D:\lavoro\sviluppo\apps\marmallade.chat\node_modules\@tensorflow\tfjs-layers\src\losses.ts:142:9
    at D:\lavoro\sviluppo\apps\marmallade.chat\node_modules\@tensorflow\tfjs-core\src\engine.ts:442:20
    at Engine.scopedRun (D:\lavoro\sviluppo\apps\marmallade.chat\node_modules\@tensorflow\tfjs-core\src\engine.ts:453:19)
    at Engine.tidy (D:\lavoro\sviluppo\apps\marmallade.chat\node_modules\@tensorflow\tfjs-core\src\engine.ts:440:17)
    at Object.tidy (D:\lavoro\sviluppo\apps\marmallade.chat\node_modules\@tensorflow\tfjs-core\src\globals.ts:192:17)
    at sparseCategoricalCrossentropy (D:\lavoro\sviluppo\apps\marmallade.chat\node_modules\@tensorflow\tfjs-layers\src\losses.ts:137:10)
    at totalLossFunction (D:\lavoro\sviluppo\apps\marmallade.chat\node_modules\@tensorflow\tfjs-layers\src\engine\training.ts:1321:22)
    at D:\lavoro\sviluppo\apps\marmallade.chat\node_modules\@tensorflow\tfjs-core\src\engine.ts:442:20
(node:13040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any idea how to resolve it?

The folder is: nlu/utterances/en/Welcome.txt

Thanks in advance.
Daniele

**Comment by elozano98** [comment]
Hello, 
In the issue, you specify that the folder is `nlu/utterances/en/Welcome.txt`, are you trying to train the model with only one intent?

**Comment by elozano98** [comment]
Hello, you specify that the folder is `nlu/utterances/en/Welcome.txt`, are you trying to train a model with only one intent?

The model **can not be trained with only one intent**, so the folder `nlu/utterances/en/` would at least contain multiple txt files according to the intents that the model has to learn to predict.

One simple example would be if the model has to learn to predict when a user greetings or farewells. In which case, the folder would contain two txt files:

1. **Welcome.txt**: Containing greetings input samples of users.
2. **Goodbye.txt**: Containing farewells input samples of users.

**Comment by crtdaniele** [comment]
Thanks for your tip.
Now working correctly, but the route doesn't work.

The route:

  {
    path: "initial",
    intent: "Welcome",
    action: Welcome,
  }

The file Welcome.txt

ciao
buongiorno
saluti
hello
buondì

In the chat, if I try to write "ciao" the route goes in 404.

Where is the error now?

Thanks in advice.
Daniele
