### ISSUE TITLE
Dependencies with known vulnerabilities

### ISSUE THREAD

**Issue by yagoff** [hubtype/botonic#1416]
The package "@botonic/plugin-nlu" in its version "0.18.0" have dependencies with known vulnerabilities. They are reported by tools like Veracode, and they should be upgraded. These are screenshot from a Veracode Analysis:

![botonic-nlu-vulnerability-3](https://user-images.githubusercontent.com/9529767/112951273-76f81580-913b-11eb-8a0c-1ab94aa35ae8.png)
![botonic-nlu-vulnerability-2](https://user-images.githubusercontent.com/9529767/112951285-795a6f80-913b-11eb-9511-18cd30c7e7fa.png)
![botonic-nlu-vulnerability-1](https://user-images.githubusercontent.com/9529767/112951289-7a8b9c80-913b-11eb-822a-ed2c7f050ce0.png)

And here are the versions of the three dependencies with the vulnerabilities fixed:

![botonic-nlu-vulnerability-6](https://user-images.githubusercontent.com/9529767/112951476-ae66c200-913b-11eb-8024-1c7e1c5e66b4.png)
![botonic-nlu-vulnerability-5](https://user-images.githubusercontent.com/9529767/112951480-af97ef00-913b-11eb-957e-d106efabb9f8.png)
![botonic-nlu-vulnerability-4](https://user-images.githubusercontent.com/9529767/112951481-af97ef00-913b-11eb-9e98-e516dcb1b869.png)

**Comment by vanbasten17** [comment]
Hi @yagoff ,`@botonic/plugin-nlu` is not supported anymore. Please use `@botonic/plugin-intent-classification` instead.
