### ISSUE TITLE
Fail when installing a template

### ISSUE THREAD

**Issue by jesusloplar** [hubtype/botonic#1744]
<img width="568" alt="Screenshot 2021-07-29 at 21 01 26" src="https://user-images.githubusercontent.com/46565164/127550873-42d8c048-6646-458f-b659-08dbc55a40cc.png">

I thought the problem was on installing the library with root permissions, but it cannot be installed anyway...

**Comment by vanbasten17** [comment]
Hi @jesusloplar , thanks for reporting! The error log doesn't seem to be related with a permissions issue.
Can you try to `cd` into your project and run `npm install` manually from there?

**Comment by jesusloplar** [comment]
Thanks for the quick response, I leave a screenshot. The error it's still the same. I may be missing something about a `react` dependency not installed? it's quite strange because i haven't seen this error anywhere online...

<img width="1380" alt="Screenshot 2021-07-30 at 11 56 01" src="https://user-images.githubusercontent.com/46565164/127636709-a4d85f37-cd9e-46ac-9f99-86bd757b37ca.png">

**Comment by vanbasten17** [comment]
By doing a quick search and as it is suggested in your terminal I have seen this: https://stackoverflow.com/a/65348395
Also trying to delete `node_modules`, `package-lock.json` and reinstall could do the trick.
`rm -rf node_modules package-lock.json` and then `npm install`. It seems to be a consequence of a bad resolution of the dependencies on installation.

**Comment by jesusloplar** [comment]
already got it solve! many thanks 😄

**Comment by jhenriqueax** [comment]
hey, same problem here! how do you solved it?
