### ISSUE TITLE
I can't select a bot when i do botonic deploy

### ISSUE THREAD

**Issue by smaiau** [hubtype/botonic#1811]
**Describe the bug**
On Windows 10, use Cygwin, cmd or powershell and run botonic deploy, you can't select the bot you want to deploy
![image (5)](https://user-images.githubusercontent.com/13879703/131182984-c40e03d6-88dd-4756-9d4e-a3ff980821a8.png)
![image (3)](https://user-images.githubusercontent.com/13879703/131182987-3d1617bd-b078-4b48-92df-b41605094f06.png)
![image (4)](https://user-images.githubusercontent.com/13879703/131182990-e9b4c7ba-a468-4a13-9199-dc6e8707259b.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Use Windows 10
2. Use Cygwin, cmd or powershell
3. Type botonic deploy
4. You can't select the bot you want to deploy

**What is the expected behaviour?**
We should saw a list of options

**About the environment**
Windows 10 Family version 21H1

**Comment by arammarm** [comment]
I have this problem too. anyone has a solution

**Comment by vanbasten17** [comment]
Yes @arammarm , you're right, this solves the issue. We have reviewed the behavior of this part in latest versions though.
