### ISSUE TITLE
I think whether there is a scroll bar that needs to be made configurable

### ISSUE THREAD

**Issue by weigaosS** [hubtype/botonic#1954]
**Describe the bug**

I have a product that displays some content through the coverComponent. The content is relatively long and will produce scroll bars.

My problem is that the scroll bar does not support wheel scrolling, it can only be dragged

I checked the source code and found that you traverse all the parent elements of the DOM element after mouseover by the mouse, and shield the mousewheel event, causing the scroll bar to fail to scroll through the wheel.

so, you can make the scroll bar configurable

**To Reproduce**
Steps to reproduce the behaviour:
5. Intuition about the error / Proposed solution (optional)

**What is the expected behaviour?**

**Screenshots**

**About the environment**
Which versions of [**botonic** packages](https://github.com/hubtype/botonic/tree/master/packages), and which browser/OS or environment (development/production) are affected by this issue? Did this work in previous versions of [**botonic** packages](https://github.com/hubtype/botonic/tree/master/packages)? 

**Additional context**

**Comment by vanbasten17** [comment]
[merged](https://github.com/hubtype/botonic/pull/1968) and published within @botonic/react's v0.20.0.
