### ISSUE TITLE
Change DialogFlow query language

### ISSUE THREAD

**Issue by herrlegno** [hubtype/botonic#1965]
**Is your feature request related to a problem? Please describe.**
The problem is that, for self-hosted version (at least) I can't set up the default language of the dialogflow query nor the Botonic bot language from the initialization script.

**Describe the solution you'd like**
Something like this maybe?:
```js
document.addEventListener('DOMContentLoaded', function (event) {
  Botonic.setDefaultLocale('es');
  Botonic.setDialogFlowLanguageCode('es-ES');
  Botonic.render(document.getElementById('root'));
});
```

**Describe alternatives you've considered**
.

**Additional context**
As I'm using DialogFlow as my NLU I need to be able to change the query languageCode to be able to respond in the language the user speak. Also been able to change the default bot i18n language from the initialization would be useful.

**Comment by vanbasten17** [comment]
[merged](https://github.com/hubtype/botonic/pull/1987) and published in @botonic/plugin-dialogflow's v0.20.0
