### ISSUE TITLE
Installing dependencies... Error

### ISSUE THREAD

**Issue by jackLiMeetKai** [hubtype/botonic#2028]
Hi, when I try to create a new bot: using `botonic new myBot blank`

I got the following error: 
<img width="885" alt="Screen Shot 2021-11-10 at 12 33 12 PM" src="https://user-images.githubusercontent.com/93943025/141189085-512e6a68-7a79-42e7-9d14-937c8ae7cd44.png">

How can I solve this? Thanks!

**Comment by vanbasten17** [comment]
Hi @jackLiMeetKai , can you please provide more information regarding your system?
Is this a Linux machine? which is the node version and which one for botonic (`botonic --version`)?
I've just tried the installation in my MacOs 10.15.17 and it's working correctly.

**Comment by appleearth008** [comment]
Hi sorry, I am this @jackLiMeetKai guy above, and I forgot to post useful information in my very first post.

I am using `macOS Monterey 12.0.1` with M1 chip.
Node version: v17.0.1
botonic version: `@botonic/cli/0.20.0 darwin-arm64 node-v17.0.1`

Thanks for getting back to me so quickly and hope you can solve my issue.
Let me know if you have more questions.

**Comment by DanielRuf** [comment]
Please see https://github.com/hubtype/botonic/issues/2042#issuecomment-970094056

This is due to how npm 7 works now.

**Comment by vanbasten17** [comment]
Closing this issue, see https://github.com/hubtype/botonic/issues/2042#issuecomment-970094056
