### ISSUE TITLE
dependencies installation failed error 

### ISSUE THREAD

**Issue by NarendraG02** [hubtype/botonic#2042]
**Describe the bug**
While executing ' botonic new myBot blank ' , dependencies installation failed error occurs. 

**System Details**
Windiow 10 64 bit
Nodejs LTS 16.13.0 is installed

**What is the expected behaviour?**
Bot should be created after execution of command

**Screenshots**
![ERROR](https://user-images.githubusercontent.com/87420430/141958206-c4f997a8-36d2-4332-ad5a-cf89b37063bb.PNG)

**About the environment**
Installed latest version of @botonic/cli 0.20.0
![image](https://user-images.githubusercontent.com/87420430/141958630-f00cc598-95fc-4aad-9317-4774cd3cdae7.png)

**Please revert back as soon as possible**  @DanielRuf @ericmarcos @gbarba @asastre @dpinol

**Comment by DanielRuf** [comment]
Not sure why I was mentioned here, I have nothing to do with this project.

You might want to try npm 6 or skip installing peer dependencies and install them yourself with the correct versions (React).

Please read https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies and try the mentioned flags:

> You have the option to retry with --force to bypass the conflict or --legacy-peer-deps command to ignore peer dependencies entirely (this behavior is similar to versions 4-6).

**Comment by DanielRuf** [comment]
See https://github.com/hubtype/botonic/commits?author=DanielRuf, I did only one small change. I am not an active contributor or maintainer of this project ;-)

**Comment by vanbasten17** [comment]
Thanks @DanielRuf for your contribution! I agree with trying npm 6 or skipping installing peer dependencies and install them after. @NarendraG02, @appleearth008 and @jackLiMeetKai you should go for this option meanwhile we try to support this.

**Comment by cci-mahhassan** [comment]
I had same issue, downgrading node js to v14 helped me install the dependencies.
