### ISSUE TITLE
I am getting error once i run botonic train

### ISSUE THREAD

**Issue by aalisher5** [hubtype/botonic#2242]
**Describe the bug**
I have created a new blank botonic project, i tried to enable nlu as per the instruction 

1. In the bot directory, enter npm install @botonic/plugin-nlu.

2. Create two types of intents, i.e. two text files called chitchat.txt and help.txt in src/nlu/utterances/en containing utterances related to an intent. You must create at least two files to make the NLU plugin work.

3. Enter the content of your choice in both files. In our example, we are going to add content to the help.txt file. Make sure to add a line break between each intent.

src/nlu/utterances/en/help.txt
4. Open src/docs/plugins.js and add @botonic/plugin-nlu into your plugins array.

5. Run botonic train. This will generate a prediction model based on the added examples.

I am getting the error 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blank@1.0.0 train:ner: `ts-node src/nlp/tasks/ner/train.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blank@1.0.0 train:ner script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above

**Comment by Gzavor** [comment]
I got the same kind of problem.

> c:\botonic\helmoBot>botonic train
> 
> > blank@1.0.0 train:intent-classification
> > ts-node src/nlp/tasks/intent-classification/train.ts
> 
> 
> > blank@1.0.0 train:ner
> > ts-node src/nlp/tasks/ner/train.ts
> 
> node:internal/modules/cjs/loader:959
>   throw err;
>   ^
> 
> Error: Cannot find module './train.ts'
> Require stack:
> - c:\botonic\helmoBot\src\nlp\tasks\ner\imaginaryUncacheableRequireResolveScript
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
>     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
>     at requireResolveNonCached (c:\botonic\helmoBot\node_modules\ts-node\dist\bin.js:549:16)
>     at getProjectSearchDir (c:\botonic\helmoBot\node_modules\ts-node\dist\bin.js:519:40)
>     at phase3 (c:\botonic\helmoBot\node_modules\ts-node\dist\bin.js:267:27)
>     at bootstrap (c:\botonic\helmoBot\node_modules\ts-node\dist\bin.js:47:30)
>     at main (c:\botonic\helmoBot\node_modules\ts-node\dist\bin.js:33:12)
>     at Object.<anonymous> (c:\botonic\helmoBot\node_modules\ts-node\dist\bin.js:579:5)
>     at Module._compile (node:internal/modules/cjs/loader:1126:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'c:\\botonic\\helmoBot\\src\\nlp\\tasks\\ner\\imaginaryUncacheableRequireResolveScript'
>   ]
> }
> child process exited with code 1Error: The specified module could not be found.
> \\?\c:\botonic\helmoBot\node_modules\@tensorflow\tfjs-node\lib\napi-v7\tfjs_binding.node
>     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
>     at Module.load (node:internal/modules/cjs/loader:1004:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
>     at Module.require (node:internal/modules/cjs/loader:1028:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (c:\botonic\helmoBot\node_modules\@tensorflow\tfjs-node\dist\index.js:58:16)
>     at Module._compile (node:internal/modules/cjs/loader:1126:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
>     at Object.require.extensions.<computed> [as .js] (c:\botonic\helmoBot\node_modules\ts-node\src\index.ts:1608:43)
>     at Module.load (node:internal/modules/cjs/loader:1004:32) {
>   code: 'ERR_DLOPEN_FAILED'
> }
> child process exited with code 1

src/nlp/tasks/ner/train.ts -> I don't have the ner folder in the bot when I install NLU

**Comment by vanbasten17** [comment]
`@botonic/plugin-nlu` is deprecated. Please use https://www.npmjs.com/package/@botonic/plugin-intent-classification
