### ISSUE TITLE
issue on deploying the  bot 

### ISSUE THREAD

**Issue by iamnaveenoff** [hubtype/botonic#2254]
**Describe the bug**
After creating a sample bot from a template  and after creating i tried botonic deploy it crashes after entering username and password

**To Reproduce**
Steps to reproduce the behaviour:
1. enter botonic deploy'
2. enter username and password
3. it will ask for use arrow to select bot 
4. but nothing comes 

**What is the expected behaviour?**
it should ask for name of the bot 

**Screenshots**
![image](https://user-images.githubusercontent.com/13293139/177909726-373466f9-2668-4725-b75a-b74643d79f5e.png)

**About the environment**
Which versions of [**botonic** packages](https://github.com/hubtype/botonic/tree/master/packages), and which browser/OS or environment (development/production) are affected by this issue? Did this work in previous versions of [**botonic** packages](https://github.com/hubtype/botonic/tree/master/packages)? 

**Additional context**

**Comment by manuelalferez** [comment]
The error is caused by the botonic configuration. This configuration is in the file `.botonic.json`. To solve the issue, try the following:

1. Delete the file `.botonic.json`
	  ```bash
	  rm .botonic.json
	  ```
2. Log out from Botonic 
	  ```bash 
	  botonic logout
	  ```
3. Deploy your bot
	  ```bash 
	  botonic deploy
	  ```
