### ISSUE TITLE
Two packages are missing at Create a Conversational App from Scratch > Add NLU

### ISSUE THREAD

**Issue by manuelalferez** [hubtype/botonic#2261]
**Describe the bug**
Following the [Create a Conversational App from Scratch tutorial](https://github.com/hubtype/botonic/blob/master/docs/docs/create-convapp.md), we just install NLU with `npm install @botonic/plugin-nlu`, which leads to error when we try `botonic train` because two packages are missing: `@botonic/plugin-ner` and `@botonic/plugin-intent-classification`.
```bash 
# output 

Training process has been stopped because you don't have @botonic/plugin-ner installed.
Please, install it with the following command:
$ npm install @botonic/plugin-ner
Training process has been stopped because you don't have @botonic/plugin-intent-classification installed.
Please, install it with the following command:
$ npm install @botonic/plugin-intent-classification
```
**To Reproduce**
Following the steps described [in the _Add NLU_ section](https://github.com/hubtype/botonic/blob/master/docs/docs/create-convapp.md?plain=1#L171-L206)
**Proposed solution**
Installing those dependences at [the time we are installing `@botonic/plugin-nlu`](https://github.com/hubtype/botonic/blob/master/docs/docs/create-convapp.md?plain=1#L173).

**About the environment**
@botonic/cli/0.20.0 darwin-x64 node-v14.20.0
node version: v14.20.0
npm version: 6.14.17

**Comment by MohitBansal321** [comment]
Hey, This issue still not resolve?
