### ISSUE TITLE
Webviews do not work in Messenger

### ISSUE THREAD

**Issue by Playmambo-Bots** [hubtype/botonic#2266]
Describe the bug
Using the tutorial template.
Webviews do not work when bot is deployed to Messenger 
Bot stops working before showing the button that opens the webview.
Node version 14.9.0
What is the expected behaviour?
Bot shows the button that opens the webview and button opens the webview.

EDIT:
Facebook has a lot of changing rules. I assume we have to code a solution for every case.

**Comment by vanbasten17** [comment]
Yes, Facebook changes its rules constantly, we try to do our best to adapt to their changes. Just tested it and webviews are working in FB with latest `@botonic/react` version.
