### ISSUE TITLE
Webchat CSS gets conflicts with website impacting the output of webchat, cover component

### ISSUE THREAD

**Issue by weconnectchat** [hubtype/botonic#2274]
**Describe the bug**
When we put javascript on website to run the chat widget. I can see on some websites the CSS of cover component gets disturbed.

**What is the expected behaviour?**
Is there any plan of supporting iFrame for the webchat?
Or
Is there any way to handle this so never webchat can get conflicted.

**Comment by vanbasten17** [comment]
Right know we are not planning to support iFrame. If you want to avoid conflicts with your CSS, refer to this 786b50eb-4670-41f0-b874-6f353b826520 and use `shadowDOM` property https://github.com/hubtype/botonic/pull/1020
