### ISSUE TITLE
Not able to install Botonic NLU module on MacBook M2.

### ISSUE THREAD

**Issue by ahrafk12** [hubtype/botonic#2291]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
5. Intuition about the error / Proposed solution (optional)

**What is the expected behaviour?**

**Screenshots**

**About the environment**
Which versions of [**botonic** packages](https://github.com/hubtype/botonic/tree/master/packages), and which browser/OS or environment (development/production) are affected by this issue? Did this work in previous versions of [**botonic** packages](https://github.com/hubtype/botonic/tree/master/packages)? 

**Additional context**

**Comment by vanbasten17** [comment]
Hi @ahrafk12 . New packages https://www.npmjs.com/package/@botonic/plugin-intent-classification and https://www.npmjs.com/package/@botonic/plugin-ner should be used instead of `@botonic/nlu`. We'll try to reproduce the bug in a M2 MacBook.
