### ISSUE TITLE
Websocket customization / support

### ISSUE THREAD

**Issue by Nitin1121** [hubtype/botonic#2296]
I have created a new botonic chatbot (blank)
On doing botonic serve chatbot appears in http://localhost:8080/.

![image](https://user-images.githubusercontent.com/53284278/216522454-738c3fc5-bce7-4e21-bf3c-9adc5a869786.png)
There is a Webocket call happening to port 8080, can we customize the url of the websocket if possible how to do it ?
If not possible how to prevent this call and write our own websocket call?
Can you help me in this

**Comment by vanbasten17** [comment]
This is not planned atm. You'll need to do a further investigation on your own way. Let us know if you need help in something.
