### ISSUE TITLE
 ERROR in ./webpack-entries/dev-entry.js

### ISSUE THREAD

**Issue by flamecopper** [hubtype/botonic#2511]
Hi there,

I have encountered this error when I was running botonic serve.

> tutorial@1.0.0 start
> webpack serve --env target=dev --mode=development

<w> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration.
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.208.10:8080/
<i> [webpack-dev-server] Content not from webpack is served from ' xxxxx/dist,  xxxxx/src/nlp/tasks' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
asset webchat.botonic.js 570 KiB [emitted] (name: main)
asset index.html 840 bytes [emitted]
runtime modules 27.3 KiB 12 modules
modules by path ./node_modules/ 179 KiB
  modules by path ./node_modules/webpack-dev-server/client/ 68.9 KiB 16 modules
  modules by path ./node_modules/webpack/ 19.8 KiB
    ./node_modules/webpack/hot/dev-server.js 1.94 KiB [built] [code generated]
    ./node_modules/webpack/hot/log.js 1.86 KiB [built] [code generated]
    + 3 modules
  modules by path ./node_modules/html-entities/lib/*.js 81.3 KiB
    ./node_modules/html-entities/lib/index.js 7.74 KiB [built] [code generated]
    ./node_modules/html-entities/lib/named-references.js 72.7 KiB [built] [code generated]
    ./node_modules/html-entities/lib/numeric-unicode-map.js 339 bytes [built] [code generated]
    ./node_modules/html-entities/lib/surrogate-pairs.js 537 bytes [built] [code generated]
  ./node_modules/ansi-html-community/index.js 4.16 KiB [built] [code generated]
  ./node_modules/process/browser.js 5.29 KiB [built] [code generated]
./webpack-entries/dev-entry.js 39 bytes [built] [code generated] [1 error]

ERROR in ./webpack-entries/dev-entry.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find package '@babel/plugin-proposal-object-rest-spread' imported from  xxxxx/babel-virtual-resolve-base.js
    at new NodeError ( xxxxx/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:203:5)
    at packageResolve ( xxxxx/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:873:9)
    at moduleResolve ( xxxxx/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:902:20)
    at defaultResolve ( xxxxx/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:985:15)
    at resolve ( xxxxx/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:999:12)
    at resolve ( xxxxx/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:13:10)
    at tryImportMetaResolve ( xxxxx/node_modules/@babel/core/lib/config/files/plugins.js:123:45)
    at resolveStandardizedNameForImport ( xxxxx/node_modules/@babel/core/lib/config/files/plugins.js:145:19)
    at resolveStandardizedName ( xxxxx/node_modules/@babel/core/lib/config/files/plugins.js:154:12)
    at loadPlugin ( xxxxx/node_modules/@babel/core/lib/config/files/plugins.js:47:20)

webpack 5.84.1 compiled with 1 error in 775 ms

I have already installed the following package:

npm list -g
/root/.nvm/versions/node/v18.16.0/lib
├── @botonic/cli@0.21.3
├── @botonic/core@0.22.0-alpha.1
├── corepack@0.17.0
├── js-beautify@1.14.7
└── npm@9.5.1

**Comment by vanbasten17** [comment]
hi @flamecopper , thanks for opening the issue! It seems there is an issue regarding this: `Error: Cannot find package '@babel/plugin-proposal-object-rest-spread'`. I have done a quick Google search and I've seen there are packages experimenting this issue as well. Take a look here: https://github.com/vaadin/flow/issues/16905#issuecomment-1567846769 
I'm closing this issue atm, let us know if you need further help, or reopen the issue when you have progressed with this
