### ISSUE TITLE
Cannot receive url parameters

### ISSUE THREAD

**Issue by bndby** [hubtype/botonic#409]
**Describe the bug**

Try to pass URL parameters (https://docs.botonic.io/tutorials-and-examples/guided-flow#working-with-url-parameters), but receive an empty params

**To Reproduce**

index.js
```
...
<Button key={site.id} path={`menu?id=${site.id}`}>
{site.title}
</Button>
...
```

menu.js
```
...
render() {
    //
    console.log('Menu', this.context.params);
...
```

result of console.log():
```
params: {
e: ""
__proto__: Object
}
```

**What is the expected behaviour?**
Url parameters in params

**About the environment**
node 12
botonic 0.10.0

 Did this work in previous versions of botonic? 
work fine on 0.9.0

**Additional context**

**Comment by vanbasten17** [comment]
Hi @bndby, thanks for your feedback! 
This bug will be fixed in the next [Botonic release](https://github.com/hubtype/botonic/pull/422).
Closing this issue.
