### ISSUE TITLE
CSS styles for webviews

### ISSUE THREAD

**Issue by bndby** [hubtype/botonic#431]
**Describe the bug**
when i try import css files in webview, css code inserted into the main html, not to webview iframe

**To Reproduce**
open any webview js file and try

```
import './any.css'
```

**What is the expected behaviour?**
want to see css stykles in webview iframe, not in parent html

**About the environment**
botonic 0.9.0
node 12.11.0

**Comment by ericmarcos** [comment]
Yes, this is a known issue we'll try to fix in a next release. Bear in mind though that when you deploy the bot and test it in a real messaging channel, the styles will work. This issue only happens in a local `botonic serve` environment.
