### ISSUE TITLE
Add the ability to pass user and password as parameter to the botonic deploy instruction of the cli

### ISSUE THREAD

**Issue by yagoff** [hubtype/botonic#463]
Right now, when I configure automatic deployments from the CI/CD pipelines of the bots using the credentials.json, it just works during a short amount of time since the expiration of the refresh_token.

It would be nice to have the ability to pass the user and password as parameters to the botonic deploy instruction so it can be done in just one instruction. Something like:
`botonic deploy -u username -p ****** --botName=chatbot1`

**Comment by guinii** [comment]
#470

**Comment by guinii** [comment]
Hey @yagoff we have merged this issue in the PR #470 into master.
We will publish it in the new release, we are happy to have your feedback :)
