### ISSUE TITLE
Avisos a un cliente de que está esperando en una cola para que le atienda un humano

### ISSUE THREAD

**Issue by ibengoa** [hubtype/botonic#481]
Consideramos que sería muy útil para un cliente que entra a la espera en una cola a que le atienda un humano, que cada cierto tiempo se le pueda escribir un mensaje que le ayude a sentirse menos desatendido, para posibles casos en que el humano está ocupado con más tareas de su trabajo y no le atiende fluidamente.

**Comment by ericmarcos** [comment]
Hola @ibengoa, gracias por reportar errores y proponer mejoras!
Iremos respondiendo a medida que haya avances.

Te quería preguntar si estás en nuestro cana de Slack (slack.botonic.io) o si eres alguno de nuestros clientes?

Saludos,

**Comment by ibengoa** [comment]
Muy buenas tardes Eric! 

Si estoy en el canal de slack, soy Iñaki de Singular Factory ;)

Saludos

**Comment by ericmarcos** [comment]
This is on our roadmap for next year, so I'm going to close it here as it's not a critical issue.
