### ISSUE TITLE
Etiqueta indicadora del día al que pertenecen los mensajes

### ISSUE THREAD

**Issue by ibengoa** [hubtype/botonic#482]
Ya sea para diferenciar entre sesiones de chat (de cuando el usuario abre el chat) o para diferenciar los mensajes del día, estaría bien poder añadir un mensaje/etiqueta configurable en estilo, en medio de los mensajes del chat, similar a lo que hace whatsapp para separar los mensajes por días.

**Comment by vanbasten17** [comment]
we are planning to add this feature in coming versions, please be aware of incoming versions
