### ISSUE TITLE
Install dependencies optional

### ISSUE THREAD

**Issue by israteneda** [hubtype/botonic#821]
**Is your feature request related to a problem? Please describe.**
When I created the bot the process of install dependencies fail.

**Describe the solution you'd like**
Then I had to install them manually

**Describe alternatives you've considered**
I consider that install dependencies could be optional, like:
Install dependencies:
- automatic
- manually

Thanks for the amazing project

**Comment by ericmarcos** [comment]
Hi @israteneda thanks for your feedback. We don't consider this to be critical, so I'm going to close this issue for now. In any case, we'll re-evaluate in the future and, as always, PRs are welcome =)
