### ISSUE TITLE
Updating the Webhook settings fails on hubtype.com with error {"feature_flags_json":["This field is required."]}

### ISSUE THREAD

**Issue by artworx** [hubtype/botonic#846]
**Describe the bug**

Updating the Webhook settings fails on hubtype.com with error `{"feature_flags_json":["This field is required."]}`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Webhook settings 
2. Click on Save 
3. See error `{"feature_flags_json":["This field is required."]}`
4. Intuition about the error / Proposed solution (optional)
Editing the request payload from `"feature_flags":{}` to `"feature_flags_json":{}` allows the request to continue and save the data. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1954578/86571191-b7927c00-bf79-11ea-9a1e-d8140e001e99.png)

**About the environment**
hubtype.com

**Comment by MarcosCA** [comment]
Hi @artworx,
Thank you for reporting the issue. We have identified the issue and we will deploy a fix soon. We will let you know when is fixed.
Thank you again.

**Comment by MarcosCA** [comment]
Hi @artworx, 
The fix for this issue has been already deployed. 
Thank you again for reporting it.
