### ISSUE TITLE
Issue running botonic serve

### ISSUE THREAD

**Issue by CrashyBang** [hubtype/botonic#911]
**Describe the bug**

I get the following error when trying to run `botonic serve`, this is a default install have tried both the `tutorial` template and `blank`.

```
Serving Botonic...

> @ start /home/user/purr-bot
> next start


> Could not find a valid build in the '/home/user/purr-bot/.next' directory! Try building your app with 'next build' before starting the server.

npm
 ERR! code ELIFECYCLE
npm ERR! errno 1

npm
ERR! @ start: `next start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-08-26T08_34_09_409Z-debug.log

child process exited with code 1
```

**To Reproduce**
Steps to reproduce the behaviour:
1. `npm install -g @botonic/cli`
2. `botonic new purr-bot tutorial`
3. `cd purr-bot`
4. `botonic serve`
5. See above error

**What is the expected behaviour?**

App to start up at localhost:8080

**Screenshots**

**About the environment**
Latest version of `botonic` and running in WSL 20,04.

**Additional context**

**Comment by dpinol** [comment]
Hi,
this looks like a "next.js" issue, are you using it? 
I don't have experience with it. Could you try repeating your tests without "next"?

**Comment by CrashyBang** [comment]
`botonic` appears to use it internally, here is the `scripts` for the generate `package.json`:

```
  "scripts": {
    "dev": "next",
    "build": "rm -rf .next && next build && cp botonic.config.js .next/",
    "start": "next start"
  },
```

**Comment by dpinol** [comment]
Hi,
I cannot find any reference to "next" in botonic. Are you sure you didn't change it locally by mistake?
Otherwise, please provide link to github.com which contains it

**Comment by CrashyBang** [comment]
Hey @dpinol looks like it is using the old `npm` package: https://www.npmjs.com/package/botonic

The `0.4.1.` release used next internally: https://github.com/hubtype/botonic/blob/4fead1ba0c2586db6ca428e4666cd31c275c2258/src/botonic.ts#L4 (there are more references as well) 

Will nuke all libs tonight and try again.

**Comment by CrashyBang** [comment]
Can confirm was wrong `cli` version.
