### ISSUE TITLE
Adding name and version fields to generated package.json

### ISSUE THREAD

**Issue by chopfitzroy** [hubtype/botonic#928]
**Describe the bug**

Currently the `cli` does not add `name` or `version` to the `package.json` this can cause [issues](https://github.com/lerna/lerna/issues/2127) when working with tools like `lerna`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Generate new project
2. Open `package.json`
3. `name` and `version` are not present

**What is the expected behaviour?**

Fields would be added, name based on name given when using `cli` and version could default to something like `0.0.0` or `1.0.0`.

**Screenshots**

**About the environment**
Which versions of [**botonic** packages](https://github.com/hubtype/botonic/tree/master/packages), and which browser/OS or environment (development/production) are affected by this issue? Did this work in previous versions of [**botonic** packages](https://github.com/hubtype/botonic/tree/master/packages)? 

Using latest `cli` version.

**Additional context**

**Comment by vanbasten17** [comment]
We have added both name and version to every template in the new [released package](https://www.npmjs.com/package/@botonic/cli/v/0.14.0). Thanks for reporting! 😊
