### ISSUE TITLE
support for target="_self" in url

### ISSUE THREAD

**Issue by rehashsathya** [hubtype/botonic#929]
**Describe the bug**
currently there is no support for url to  be opened in the same webchat window.
when we host the website and give links within our website, the url opens in a new browser window and a new chathead is displayed.

**What is the expected behaviour?**
support for target="_self" will have better approach when we have links in the bot pointing to our own website.
This needs to ensure that the chat window opened is active the session remains the same but the url in the background changes.

**Comment by ericmarcos** [comment]
Nice catch, we're working on it and it will be available in the release 0.15

**Comment by vanbasten17** [comment]
Hi @rehashsathya! We have merged this new feature and will be added in the next release! We are very happy to receive your feedback! Let us know if you have more suggestions or issues 😊
