### ISSUE TITLE
Support for Knowledgebase and samll talk in dialogflow.

### ISSUE THREAD

**Issue by rehashsathya** [hubtype/botonic#930]
**Is your feature request related to a problem? Please describe.**
Currently we cannot get the intent matching for knowledgebase or smalltalk in botonic

**Describe the solution you'd like**
The support for knowledgebase and smalltalk will help in creating better FAQ bots using dialogflow.

**Describe alternatives you've considered**
Currently we have no options other than creating intent for every Q&A

**Comment by ericmarcos** [comment]
Hi @rehashsathya, thanks for submitting this feature request. It's not on our roadmap for this year but we'll add it to our backlog for next year. I'll close this issue for now.

As always, PRs are welcome too =)
