### ISSUE TITLE
Botonic.clearMessages() doesn't delete all messages

### ISSUE THREAD

**Issue by a-rus** [hubtype/botonic#941]
**Describe the bug**
I am triggering this function (clearMessages) if the lastMessageUpdate is older than 3 hours- from onInit or onStart - but sometimes not all the messages are being deleted. Some of the messages that still remain (custom message types) are being shown as an empty chat bubble.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add the clearMessages in onOpen  if lastMessageUpdate is older than 3 hours 
2. Open chatbot
3. Add some messages
4. Leave the browser and the chatbot open (I suspect this has something to do with this behavior - if I do everything the same but instead I close the browser/tab and reopen it 3 hours later then I don't get this problem)
5. Notice some older messages - not necessary chronologically linked- , and some empty chat bubbles instead of the custom types messages

**What is the expected behaviour?**
No message to be present

**Screenshots**
![image](https://user-images.githubusercontent.com/18574194/93790347-9a498180-fc3b-11ea-8d25-30e118b3dee6.png)

**About the environment**
Which version: **"@botonic/react": "^0.14.0-alpha.4"** 
Which browser/OS or environment (development/production) are affected by this issue: Any browser and OS, more frequently noticed in IE11 and Edge.
Did this work in previous versions: **no** 

**Additional context**
The botonic state when this happened:
`{"user":{"id":"67f2da2b-6233-4406-85b5-7a6fbd51bc89","name":"Windows Edge","extra_data":{"lang":"GB_en"},"orderNumber":"w612222"},"messages":[{"id":"8f056d8013a54774b02f0478b7f31bac","type":"text","data":{"text":"No problem. You can find your order number on the order confirmation email we sent you.\n\nHave you found your order number?"},"timestamp":"Sep 11, 8:31:17 AM","markdown":true,"from":"bot","buttons":[],"delay":0,"typing":0,"replies":[{"payload":"enterOrderNumber","text":"Yes, I have it"},{"payload":"iDontHaveIt","text":"No, I don't have it"}],"display":true,"ack":1},{"id":"72ad013e24d645bba2148c93e2bfeaa4","type":"text","data":{"text":""},"timestamp":"Sep 11, 8:31:17 AM","markdown":true,"from":"bot","buttons":[],"delay":0,"typing":0,"replies":[{"payload":"iDontKnowTheNumber","text":"I don't have my order number"}],"display":true,"ack":1},{"id":"2c73f78d6c4740cbb8db737168c4f8c1","type":"custom","data":{"id":"2c73f78d6c4740cbb8db737168c4f8c1","json":{"placeholder":"W123456789","label":"Order Number:","text":"Welcome to the order tracking service.\n\nSo we can assist you, please enter your full order number which starts with a letter followed by a sequence of numbers","replyText":"I don't have my order number","replyPayload":"iDontKnowTheNumber","customTypeName":"messageWithInput"},"placeholder":"W123456789","label":"Order Number:","text":"Welcome to the order tracking service.\n\nSo we can assist you, please enter your full order number which starts with a letter followed by a sequence of numbers","replyText":"I don't have my order number","replyPayload":"iDontKnowTheNumber","customTypeName":"messageWithInput"},"timestamp":"Sep 11, 8:31:18 AM","from":"bot","buttons":[],"delay":0,"typing":0,"replies":[],"display":true,"customTypeName":"messageWithInput","ack":1}],"session":{"user":{"extra_data":{"lang":"GB_en"},"orderNumber":"w612222"}},"lastRoutePath":null,"devSettings":{},"lastMessageUpdate":"2020-09-11T05:31:18.375Z"}`

**Comment by vanbasten17** [comment]
Thanks for reporting @a-rus . We are closing this issue as it hasn't been possible to reproduce the bug in dev and production environments with the specified version.
